"""initial_schema_with_all_tables

Revision ID: 9a7e62c2bcc0
Revises: 
Create Date: 2026-08-25 17:17:55.624978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '9a7e62c2bcc0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('revenue_weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('incidents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp_start', sa.DateTime(), nullable=False),
    sa.Column('timestamp_end', sa.DateTime(), nullable=True),
    sa.Column('root_cause_service_id', sa.Uuid(), nullable=True),
    sa.Column('root_cause_type', sa.String(length=100), nullable=True),
    sa.Column('confidence_at_detection', sa.Float(), nullable=True),
    sa.Column('is_multi_root_cause', sa.Boolean(), nullable=False),
    sa.Column('resolution_action', sa.Text(), nullable=True),
    sa.Column('was_false_positive', sa.Boolean(), nullable=False),
    sa.Column('learned_pattern_tag', sa.String(length=100), nullable=True),
    sa.Column('anomaly_signature', pgvector.sqlalchemy.vector.VECTOR(dim=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['root_cause_service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_incidents_false_positive', 'incidents', ['was_false_positive'], unique=False)
    op.create_index('idx_incidents_root_cause_type', 'incidents', ['root_cause_type'], unique=False)
    op.create_table('metrics_raw',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_metrics_service_time', 'metrics_raw', ['service_id', sa.literal_column('recorded_at DESC')], unique=False)
    op.create_index('idx_metrics_type', 'metrics_raw', ['metric_type'], unique=False)
    op.create_table('service_dependencies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('from_service_id', sa.Uuid(), nullable=False),
    sa.Column('to_service_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['from_service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_service_id', 'to_service_id')
    )
    op.create_table('anomalies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('z_score', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_anomalies_detected_at', 'anomalies', [sa.literal_column('detected_at DESC')], unique=False)
    op.create_index('idx_anomalies_incident', 'anomalies', ['incident_id'], unique=False)
    op.create_table('blast_radius_predictions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('predicted_service_id', sa.Uuid(), nullable=False),
    sa.Column('predicted_eta_seconds', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('was_correct', sa.Boolean(), nullable=True),
    sa.Column('predicted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['predicted_service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_affected_services',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('propagation_order', sa.Integer(), nullable=False),
    sa.Column('affected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ias_incident', 'incident_affected_services', ['incident_id', 'propagation_order'], unique=False)
    op.create_table('runbook_suggestions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('root_cause_type', sa.String(length=100), nullable=False),
    sa.Column('suggested_action', sa.Text(), nullable=False),
    sa.Column('was_approved', sa.Boolean(), nullable=True),
    sa.Column('suggested_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppressions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('triggering_anomaly_id', sa.Uuid(), nullable=False),
    sa.Column('matched_incident_id', sa.Uuid(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('suppressed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['matched_incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['triggering_anomaly_id'], ['anomalies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suppressions')
    op.drop_table('runbook_suggestions')
    op.drop_index('idx_ias_incident', table_name='incident_affected_services')
    op.drop_table('incident_affected_services')
    op.drop_table('blast_radius_predictions')
    op.drop_index('idx_anomalies_incident', table_name='anomalies')
    op.drop_index('idx_anomalies_detected_at', table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_table('service_dependencies')
    op.drop_index('idx_metrics_type', table_name='metrics_raw')
    op.drop_index('idx_metrics_service_time', table_name='metrics_raw')
    op.drop_table('metrics_raw')
    op.drop_index('idx_incidents_root_cause_type', table_name='incidents')
    op.drop_index('idx_incidents_false_positive', table_name='incidents')
    op.drop_table('incidents')
    op.drop_table('services')
    # ### end Alembic commands ###
